name: ml-pred-fail
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - matplotlib
  - nb_conda_kernels
  - numpy
  - pandas
  - python=3.10
  - pytorch
  - scikit-learn
  - scipy
  - seaborn
  - tqdm